### ISSUE TITLE
Cant login to admin panel

### ISSUE THREAD

**Issue by NurvX** [mbpictures/tessera#89]
Hi,

I have deployed this project on vercel, I cant seem to login to the admin panel. 
After login I only see this page - 
![image](https://github.com/mbpictures/tessera/assets/31729691/be57fce0-d0b0-4547-915e-0451cd9ee069)

No errors in the logs - 
![image](https://github.com/mbpictures/tessera/assets/31729691/21ad430e-2e25-4aae-adff-d8bee4de1461)

Environment variables below - so far I have defined these 
![image](https://github.com/mbpictures/tessera/assets/31729691/3dbbd1b2-06f8-4e9a-ab97-d28d2bb45ac6)

**Comment by mbpictures** [comment]
Hi, and thanks for reaching out!
Please update your environment variables as in the .env.example file:
```
NEXTAUTH_URL=http://localhost:3000/api/admin/auth
NEXT_PUBLIC_SHOP_DOMAIN=http://localhost:3000
NEXT_PUBLIC_NEXTAUTH_PATH=/api/admin/auth
```
You'll need all of these three (+ ```NEXTAUTH_SECRET```) with the domain of the first two values updated to your domain (the third variable is constant, but is necessary as well).

**Comment by mbpictures** [comment]
Closing due inactivity
